---
- name: restart tomcat 
  service: name=tomcat state=restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'    

- name: restart tomcat 
  service: name=tomcat7 state=restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'    
  
- name: restart iptables
  service: name=iptables state=restarted
